[workspace]
members = ["asn1_type", "axdr_macro"]

[package]
name = "dlt698_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
axdr_macro = { path = "./axdr_macro" }
asn1_type = { path = "./asn1_type" }
anyhow = "1"
hex = "0"
num_enum = "0"
enumx_derive = "0"
thiserror = "2"
strum = "0"
strum_macros = "0"
modular-bitfield = "0"
