mod connect_request;
mod connect_response;

use asn1_type::FixedBitString;

type ProtocolConformance = FixedBitString<64, 8>;
type FunctionConformance = FixedBitString<128, 16>;

enum ProtocolConformanceFlags {
    ApplicationAssociation = 0,
    GetNormal = 1,
    GetWithList = 2,
    GetRecord = 3,
    GetProxy = 4,
    GetProxyRecord = 5,
    GetSubsequentFrame = 6,
    SetNormal = 7,
    SetWithList = 8,
    SetWithGet = 9,
    SetProxy = 10,
    SetProxyWithGet = 11,
    ActionNormal = 12,
    ActionWithList = 13,
    ActionThenGet = 14,
    ActionProxy = 15,
    ActionProxyWithGet = 16,
    ActiveEventReport = 17,
    EventTailReport = 18,
    EventRequestAccessBitReport = 19,
    SlicingService = 20,
    GetRequestSlicing = 21,
    GetResponseSlicing = 22,
    SetRequestSlicing = 23,
    SetResponseSlicing = 24,
    ActionRequestSlicing = 25,
    ActionResponseSlicing = 26,
    ProxyRequestSlicing = 27,
    ProxyResponseSlicing = 28,
    EventReportSlicing = 29,
    Dlt645_2007 = 30,
    SecurityTransmission = 31,
    ObjectPropertyID0ReadAccess = 32,
    ObjectPropertyID0SetAccess = 33,
}

enum FunctionConformanceFlags {
    ActiveEnergyMetering = 0,
    BidirectionalActiveEnergyMetering = 1,
    ReactiveEnergyMetering = 2,
    ApparentEnergyMetering = 3,
    ActivePowerDemand = 4,
    ReactivePowerDemand = 5,
    ApparentPowerDemand = 6,
    MultiRate = 7,
    ValveControl = 8,
    LocalLoadControl = 9,
    RemoteLoadControl = 10,
    FundamentalActiveEnergy = 11,
    HarmonicActiveEnergy = 12,
    HarmonicContent = 13,
    WaveformDistortion = 14,
    MultiFunctionTerminalOutput = 15,
    EventRecording = 16,
    EventReporting = 17,
    TemperatureMeasurement = 18,
    StatusMonitoring = 19,
    EthernetCommunication = 20,
    InfraredCommunication = 21,
    BluetoothCommunication = 22,
    MultimediaAcquisition = 23,
    Cascading = 24,
    DirectCurrentSimulation = 25,
    WeakPowerOutput = 26,
    TableSearch = 27,
    ThreePhaseLoadBalancing = 28,
    Upgrade = 29,
    Comparison = 30,
}
